version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - hardhat-node

  hardhat-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npx hardhat node
    ports:
      - "8545:8545"
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
